name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }} 

    - name: Remove main application class
      run: |
        rm -f src/main/java/com/fstech/MsBaseApplication.java
        rm -f src/test/java/com/fstech/MsBaseApplicationTests.java
        rm -f src/main/java/com/fstech/application/controller/MockController.java

    - name: Modify POM for library publication
      run: |
        sed -i '/<build>/,/<\/build>/d' pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
